name: CI Pipeline
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        working-directory: ci-cd-gitops-project
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Lint
        run: npm run lint || true
      - name: Build Docker Image
        run: docker build -t backend .
