name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ci-cd-gitops-project

      - name: Debug - List Files
        run: ls -R ci-cd-gitops-project

      - name: Install Backend Dependencies
        working-directory: ci-cd-gitops-project/backend
        run: npm install
      
      - name: Run Backend Tests
        working-directory: ci-cd-gitops-project/backend
        run: npx jest --coverage

      - name: Run Frontend Tests
        working-directory: ci-cd-gitops-project/frontend
        run: npx jest --coverage

      - name: Install Frontend Dependencies
        working-directory: ci-cd-gitops-project/frontend
        run: npm install

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ci-cd-gitops-project

      - name: Debug - List Files
        run: ls -R ci-cd-gitops-project

      - name: Run Backend Tests
        working-directory: ci-cd-gitops-project/backend
        run: npm test

      - name: Run Frontend Tests
        working-directory: ci-cd-gitops-project/frontend
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ci-cd-gitops-project

      - name: Debug - List Files
        run: ls -R ci-cd-gitops-project

      - name: Build Backend Docker Image
        working-directory: ci-cd-gitops-project/backend
        run: docker build -t my-backend-app .

      - name: Build Frontend Docker Image
        working-directory: ci-cd-gitops-project/frontend
        run: docker build -t my-frontend-app .

      - name: Push Backend Docker Image (Optional)
        run: echo "Pushing backend image to registry"

      - name: Push Frontend Docker Image (Optional)
        run: echo "Pushing frontend image to registry"

      - name: Apply Kubernetes Manifests
        working-directory: ci-cd-gitops-project/manifests
        run: kubectl apply -f deployment-blue.yaml -f deployment-green.yaml -f ingress.yaml -f service.yaml
